# Generated by Django 3.1.5 on 2021-02-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210214_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
