# Generated by Django 3.1.5 on 2021-02-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210212_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='task',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
