# Generated by Django 3.1.5 on 2021-02-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210214_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='attendance',
            name='month',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
