# Generated by Django 3.1.5 on 2021-02-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210212_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
