# Generated by Django 3.1.5 on 2021-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210301_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(),
        ),
    ]
