# Generated by Django 3.1.5 on 2021-02-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210212_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='perDaySalary',
        ),
    ]
