# Generated by Django 3.1.5 on 2021-02-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='task',
            field=models.TextField(blank=True, default='no task for today', null=True),
        ),
    ]
